development:
  forest_env_secret: 34a43eb61ef6aa64eab8cb28332d0ef87ed61d2381032f0824781e7cdfc74990
  forest_auth_secret: sBLV9-VzK6eiZS5q67H5wg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
